model = "gpt-5.3-codex"
model_reasoning_effort = "high"

[projects."/Users/korneel/dev/projects/pienter/garmin-timer"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/pienter/config"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/democrazy"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/verhelst"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/flow"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/ascendere"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/musicmania"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/dry"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/tnt/dry-aws"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/verenig/full_stack"]
trust_level = "trusted"

[projects."/Users/korneel/dev/projects/pienter/cli-tools"]
trust_level = "trusted"

[mcp_servers.figma]
url = "http://127.0.0.1:3845/mcp"
enabled = false

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
bearer_token_env_var = "CONTEXT7_API_KEY"
enabled = false

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest", "--channel=dev"]
enabled = false

[mcp_servers.shortcut]
command = "npx"
args = ["-y", "@shortcut/mcp@latest"]
env_vars = ["SHORTCUT_API_TOKEN"]

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[features]
collab = true
apps = true
